version: '3.3'

networks:
  sn_net:
    driver: bridge

services:
  db-master:
    image: mysql:5.7
    restart: always
    command:
      - mysqld
      - --max_connections=2500
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_REPLICATION_MODE: 'master'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306'
    expose:
      - '3306'

    networks:
      - sn_net

  db-slave:
    image: mysql:5.7
    restart: always
    command:
      - mysqld
      - --max_connections=2500
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_REPLICATION_MODE: 'slave'
      MYSQL_MASTER_HOST: 'db-master'
      MYSQL_MASTER_PORT_NUMBER: '3306'
      MYSQL_MASTER_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306'

    depends_on:
      - db-master
    networks:
      - sn_net

  liquibase:
    build:
      context: ./db-migrations/
    command: update
    restart: on-failure
    container_name: liquibase
    environment:
      - LIQUIBASE_CHANGELOG=changelog.xml
      - LIQUIBASE_URL=jdbc:mysql://db-master:3306
      - LIQUIBASE_USERNAME=user
      - LIQUIBASE_PASSWORD=password
      - LIQUIBASE_OPTS=--defaultSchemaName=db --liquibaseSchemaName=db
    depends_on:
      - db-master
    networks:
      - sn_net
