version: '3.3'

networks:
  sn_net:
    driver: bridge

services:
#  db-master:
#    image: mysql:5.7
#    restart: always
#    command:
#      - mysqld
#      - --max_connections=2500
#    environment:
#      MYSQL_DATABASE: 'db'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'user'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'password'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'password'
#      MYSQL_REPLICATION_MODE: 'master'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      - '3306'
#
#  liquibase:
#    build:
#      context: ./db-migrations/
#    command: update
#    restart: on-failure
#    container_name: liquibase
#    environment:
#      - LIQUIBASE_CHANGELOG=changelog.xml
#      - LIQUIBASE_URL=jdbc:mysql://db-master:3306
#      - LIQUIBASE_USERNAME=user
#      - LIQUIBASE_PASSWORD=password
#      - LIQUIBASE_OPTS=--defaultSchemaName=db --liquibaseSchemaName=db
#    depends_on:
#      - db-master
#    networks:
#      - sn_net

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --maxmemory 15gb --maxmemory-policy allkeys-lru --maxclients 200000
    ports:
      - 6379:6379
    networks:
      - sn_net

  rabbitmq:
    build:
      context: rabbit
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: '!SecretCookie!'
    networks:
      - sn_net
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbit/rabbitmq-data:/var/lib/rabbitmq
      - ./rabbit/rabbitmq-logs:/var/log/rabbitmq

  tarantool:
    image: tarantool/tarantool:2.6.0
    restart: on-failure
    container_name: tarantool
    volumes:
      - ./tarantool:/usr/local/share/tarantool
    command: tarantool /usr/local/share/tarantool/example.lua
    ports:
      - 3301:3301
    depends_on:
      - db-master
    networks:
      - sn_net
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: admin