version: '3.3'

networks:
  sn_net:
    driver: bridge

services:

  db-dialog:
    image: postgres:11
    container_name: dialog_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - 9118:5432
    networks:
      - sn_net

  liquibase-pg:
    build:
      context: ./db-migrations/postgresql/
    command: update
    restart: on-failure
    container_name: liquibase-pg
    environment:
      - LIQUIBASE_CHANGELOG=changelog.xml
      - LIQUIBASE_URL=jdbc:postgresql://db-dialog:5432/postgres
      - LIQUIBASE_USERNAME=user
      - LIQUIBASE_PASSWORD=pass
      - LIQUIBASE_OPTS=--defaultSchemaName=public --liquibaseSchemaName=public
    depends_on:
      - db-dialog
    networks:
      - sn_net

  db-master:
    image: mysql:5.7
    restart: always
    volumes:
      - ./configs/my-cnf/my.cnf:/etc/mysql/conf.d/my.cnf
    command:
      - mysqld
      - --max_connections=2500
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_REPLICATION_MODE: 'master'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - sn_net

  liquibase:
    build:
      context: ./db-migrations/my-sql/
    command: update
    restart: on-failure
    container_name: liquibase
    environment:
      - LIQUIBASE_CHANGELOG=changelog.xml
      - LIQUIBASE_URL=jdbc:mysql://db-master:3306
      - LIQUIBASE_USERNAME=user
      - LIQUIBASE_PASSWORD=password
      - LIQUIBASE_OPTS=--defaultSchemaName=db --liquibaseSchemaName=db
    depends_on:
      - db-master
    networks:
      - sn_net

  tarantool:
    image: tarantool/tarantool:2.6.0
    restart: on-failure
    container_name: tarantool
    volumes:
      - ./tarantool:/usr/local/share/tarantool
    command: tarantool /usr/local/share/tarantool/example.lua
    ports:
      - 3301:3301
    depends_on:
      - db-master
    networks:
      - sn_net
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: admin

#  tarantool-repl:
#    build:
#      context: ./tarantool/
#    restart: on-failure
#    #command: tail -F anything
#    command: ./mysql-tarantool-replication/replicatord
#    volumes:
#    - /sys/fs/cgroup:/sys/fs/cgroup
#    - ./tarantool/replicatord.yml:/usr/local/etc/replicatord.yml
#    privileged: true
#    container_name: tarantool-repl
#    depends_on:
#      - db-master
#    networks:
#      - sn_net
