version: '3.7'

services:
  mysql:
    image: 'percona:8.0'
    container_name: db-master
    volumes:
      - ./build_env/mysql/master.cnf:/etc/my.cnf.d/repl.cnf
      - ./build_env/mysql/master.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

  mysqlread1:
    image: 'percona:8.0'
    container_name: db-slave1
    volumes:
      - ./build_env/mysql/slave1.cnf:/etc/my.cnf.d/repl.cnf
      - ./build_env/mysql/slave_1.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4406:3306'

  mysqlread2:
    image: 'percona:8.0'
    container_name: db-slave2
    volumes:
      - ./build_env/mysql/slave2.cnf:/etc/my.cnf.d/repl.cnf
      - ./build_env/mysql/slave_1.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5506:3306'
